# Data from https://www.metropolitan.bg/shema/karta-metro
SOFIA_METRO_TRUE_FALSE_MAPPING = {
    "7th 11th kilometer": True,
    # А
    "Abdovica": False,
    # Б
    "Banishora": True,
    "Belite brezi": False,
    "Benkovski": False,
    "Borovo": False,
    "Botunets": False, 
    "Botunets 2": False,
    "Boyana": False,
    "Bukston": False,
    # В
    "Vitosha": False,
    "Voenna rampa": False,
    "Vrajdebna": False,
    "Vrybnitsa 1": True,
    "Vrybnitsa 2": True,
    # Г
    "Gevgeliski": True,
    "Geo Milev": False,
    "Gorna Banya": False,
    "Gorublyane": False,
    "Gotse Delchev": False,
    "Gradina": False,
    # Д
    "Dianabad": False,
    "Dimityr Milenkov": False,
    "Doktorski pametnik": False,
    "Dragalevtsi": False,
    "Drujba 1": True,
    "Drujba 2": True,
    "Durvenitsa": True,
    # Е
    "Eksperimentalen": False,
    # З
    "Zapaden park": True,
    "Zaharna fabrika": False,
    "Zona B-18": False,
    "Zona B-19": False,
    "Zona B-5": False,
    "Zona B-5-3": False,
    # И
    "Ivan Vazov": False,
    "Izgrev": True,
    "Iztok": True,
    "Ilinden": True,
    "Iliantsi": False,
    # К
    "Karpuzitsa": False,
    "Knyajevo": False,
    "Krasna polyana 1": False,
    "Krasna polyana 2": False,
    "Krasna polyana 3": False,
    "Krasno selo": True,
    "Kremikovtsi": False,
    "Krystova vada": False,
    # Л
    "Lagera": True,
    "Levski": False,
    "Levski V": False,
    "Levski G": False,
    "Letishte Sofia": True,
    "Lozenets": True,
    "Lulin - centyr": True,
    "Lulin 1": True,
    "Lulin 2": False,
    "Lulin 3": False,
    "Lulin 4": False,
    "Lulin 5": False,
    "Lulin 6": False,
    "Lulin 7": True,
    "Lulin 8": True,
    "Lulin 9": False,
    "Lulin 10": True,
    # М
    "Malashevtsi": False,
    "Malinova dolina": False,
    "Manastirski livadi": False,
    "Medicinska akademia": True,
    "Mladost 1": True,
    "Mladost 1A": True,
    "Mladost 2": True,
    "Mladost 3": True,
    "Mladost 4": True,
    "Moderno predgradie": False,
    "Musagenitsa": True,
    # Н
    "Nadejda 1": True,
    "Nadejda 2": True,
    "Nadejda 3": False,
    "Nadejda 4": False,
    "NPZ Iztok": False,
    "NPZ Iskyr": True,
    "NPZ Sredets": False,
    "NPZ Hadji Dimityr":False,
    # О
    "Obelya": False,
    "Obelya 1": True,
    "Obelya 2": False,
    "Oborishte": False,
    "Ovcha kupel":False,
    "Ovcha kupel 1": False,
    "Ovcha kupel 2": False,
    "Orlandovci": True,
    # П
    "Pavlovo": False,
    "PZ Iliyanci": False,
    "PZ Hladilnika": True,
    "Poduyane": False,
    "Poligona": False,
    # Р
    "Razsadnika": False,
    "Reduta": False ,
    "Republika": False,
    "Republika 2": False,
    # C
    "Sveta Troica": False,
    "Svoboda": False,
    "Serdika": False,
    "Seslavci":False,
    "Simeonovo": False,
    "Slavia": False,
    "Slatina": False ,
    "SPZ Moderno predgradie": False,
    "SPZ Slatina": False,
    "Strelbishte": True ,
    "Studentski grad": False ,
    "Suhata reka": False,
    "Suhodol": False,
    # Т
    "Tolstoy": True,
    "Trebich": False,
    "Triygylnika": True,
    # Ф
    "Fakulteta": False,
    "Filipovci": False,
    "Fondovi jilishta": False,
    # Х
    "Hadji Dimityr": True,
    "Hipodruma": True,
    "Hladilnika": True,
    "Hristo Botev": False,
    # Ц
    "Centyr": True,
    # Ч
    "Chelopechene": False,
    # Я
    "Yavorov": False
}

SOFIA_HOSPITALS_TRUE_FALSE_MAPPING = {
    "7th 11th kilometer": True,
    # А
    "Abdovica": False,
    # Б
    "Banishora": True,
    "Belite brezi": False,
    "Benkovski": False,
    "Borovo": True,
    "Botunets": True,
    "Botunets 2": False,
    "Boyana": False,
    "Bukston": False,
    # В
    "Vitosha": False,
    "Voenna rampa": False,
    "Vrajdebna": False,
    "Vrybnitsa 1": False,
    "Vrybnitsa 2": False,
    # Г
    "Gevgeliski": False,
    "Geo Milev": True,
    "Gorna Banya": True,
    "Gorublyane": False,
    "Gotse Delchev": False,
    "Gradina": False,
    # Д
    "Dianabad": False,
    "Dimityr Milenkov": False,
    "Doktorski pametnik": False,
    "Dragalevtsi": False,
    "Drujba 1": False,
    "Drujba 2": False,
    "Durvenitsa": True,
    # Е
    "Eksperimentalen": False,
    # З
    "Zapaden park": False,
    "Zaharna fabrika": False,
    "Zona B-18": True,
    "Zona B-19": False,
    "Zona B-5": False,
    "Zona B-5-3": True,
    # И
    "Ivan Vazov": True,
    "Izgrev": False,
    "Iztok": True,
    "Ilinden": True,
    "Iliantsi": False,
    # К
    "Karpuzitsa": True,
    "Knyajevo": False,
    "Krasna polyana 1": False,
    "Krasna polyana 2": True,
    "Krasna polyana 3": False,
    "Krasno selo": False,
    "Kremikovtsi": False,
    "Krystova vada": True,
    # Л
    "Lagera": False,
    "Levski": False,
    "Levski V": False,
    "Levski G": False,
    "Letishte Sofia": False,
    "Lozenets": False,
    "Lulin - centyr": False,
    "Lulin 1": False,
    "Lulin 2": False,
    "Lulin 3": False,
    "Lulin 4": False,
    "Lulin 5": False,
    "Lulin 6": True,
    "Lulin 7": False,
    "Lulin 8": False,
    "Lulin 9": True,
    "Lulin 10": False,
    # М
    "Malashevtsi": False,
    "Malinova dolina": False,
    "Manastirski livadi": True ,
    "Medicinska akademia": True,
    "Mladost 1": True,
    "Mladost 1A": False,
    "Mladost 2": True,
    "Mladost 3": True,
    "Mladost 4": False,
    "Moderno predgradie": False,
    "Musagenitsa": False,
    # Н
    "Nadejda 1": True,
    "Nadejda 2": False,
    "Nadejda 3": False,
    "Nadejda 4": False,
    "NPZ Iztok": False,
    "NPZ Iskyr": True,
    "NPZ Sredets": False,
    "NPZ Hadji Dimityr": True,
    # О
    "Obelya": False,
    "Obelya 1": False,
    "Obelya 2": True,
    "Oborishte": True,
    "Ovcha kupel": False,
    "Ovcha kupel 1": True,
    "Ovcha kupel 2": True,
    "Orlandovci": True,
    # П
    "Pavlovo": True,
    "PZ Iliyanci": False,
    "PZ Hladilnika": True,
    "Poduyane": False,
    "Poligona": True,
    # Р
    "Razsadnika": True,
    "Reduta": False,
    "Republika": False,
    "Republika 2": False,
    # C
    "Sveta Troica": False,
    "Svoboda": True,
    "Serdika": False,
    "Seslavci": False,
    "Simeonovo": False,
    "Slavia": True,
    "Slatina": False,
    "SPZ Moderno predgradie": False,
    "SPZ Slatina": False,
    "Strelbishte": True,
    "Studentski grad": False,
    "Suhata reka": True,
    "Suhodol": False,
    # Т
    "Tolstoy": False,
    "Trebich": False,
    "Triygylnika": False,
    # Ф
    "Fakulteta": False,
    "Filipovci": False,
    "Fondovi jilishta": False,
    # Х
    "Hadji Dimityr": True,
    "Hipodruma": True,
    "Hladilnika": True,
    "Hristo Botev": False,
    # Ц
    "Centyr": True,
    # Ч
    "Chelopechene": False,
    # Я
    "Yavorov": False
}

# Data from Google maps
SOFIA_NEIGHBOURHOOD_SUPERMARKET_MAPPING = {
    "7th 11th kilometer": 1,
    # А
    "Abdovica": 0,
    # Б
    "Banishora": 1,
    "Belite brezi": 0,
    "Benkovski": 0,
    "Borovo": 1,
    "Botunets": 0,
    "Botunets 2": 0,
    "Boyana": 0,
    "Bukston": 1,
    # В
    "Vitosha": 0,
    "Voenna rampa": 0,
    "Vrajdebna": 0,
    "Vrybnitsa 1": 1,
    "Vrybnitsa 2": 0,
    # Г
    "Gevgeliski": 0,
    "Geo Milev": 0,
    "Gorna Banya": 0,
    "Gorublyane": 0,
    "Gotse Delchev": 0,
    "Gradina": 0,
    # Д
    "Dianabad": 2,
    "Dimityr Milenkov": 0,
    "Doktorski pametnik": 0,
    "Dragalevtsi": 0,
    "Drujba 1": 1,
    "Drujba 2": 3,
    "Durvenitsa": 0,
    # Е
    "Eksperimentalen": 0,
    # З
    "Zapaden park": 1,
    "Zaharna fabrika": 0,
    "Zona B-18": 0,
    "Zona B-19": 0,
    "Zona B-5": 0,
    "Zona B-5-3": 1,
    # И
    "Ivan Vazov": 0,
    "Izgrev": 0,
    "Iztok": 2,
    "Ilinden": 0,
    "Iliantsi": 0,
    # К
    "Karpuzitsa": 0,
    "Knyajevo": 0,
    "Krasna polyana 1": 1,
    "Krasna polyana 2": 0,
    "Krasna polyana 3": 0,
    "Krasno selo": 3,
    "Kremikovtsi": 0,
    "Krystova vada": 0,
    # Л
    "Lagera": 0,
    "Levski": 0,
    "Levski V": 1,
    "Levski G": 2,
    "Letishte Sofia": 0,
    "Lozenets": 2,
    "Lulin - centyr": 0,
    "Lulin 1": 0,
    "Lulin 2": 1,
    "Lulin 3": 0,
    "Lulin 4": 0,
    "Lulin 5": 0,
    "Lulin 6": 2,
    "Lulin 7": 0,
    "Lulin 8": 0,
    "Lulin 9": 0,
    "Lulin 10": 0,
    # М
    "Malashevtsi": 1,
    "Malinova dolina": 1,
    "Manastirski livadi": 0,
    "Medicinska akademia": 0,
    "Mladost 1": 1,
    "Mladost 1A": 1,
    "Mladost 2": 1,
    "Mladost 3": 2,
    "Mladost 4": 3,
    "Moderno predgradie": 0,
    "Musagenitsa": 1,
    # Н
    "Nadejda 1": 0,
    "Nadejda 2": 1,
    "Nadejda 3": 2,
    "Nadejda 4": 1,
    "NPZ Iztok": 0,
    "NPZ Iskyr": 0,
    "NPZ Sredets": 0,
    "NPZ Hadji Dimityr": 2,
    # О
    "Obelya": 0,
    "Obelya 1": 0,
    "Obelya 2": 1,
    "Oborishte": 1,
    "Ovcha kupel": 0,
    "Ovcha kupel 1": 2,
    "Ovcha kupel 2": 1,
    "Orlandovci": 1,
    # П
    "Pavlovo": 1,
    "PZ Iliyanci": 0,
    "PZ Hladilnika": 2,
    "Poduyane": 0,
    "Poligona": 0,
    # Р
    "Razsadnika": 0,
    "Reduta": 1,
    "Republika": 1,
    "Republika 2": 0,
    # C
    "Sveta Troica": 3,
    "Svoboda": 0,
    "Serdika": 0,
    "Seslavci": 0,
    "Simeonovo": 1,
    "Slavia": 0,
    "Slatina": 0,
    "SPZ Moderno predgradie": 0,
    "SPZ Slatina": 1,
    "Strelbishte": 0,
    "Studentski grad": 1,
    "Suhata reka": 0,
    "Suhodol": 0,
    # Т
    "Tolstoy": 0,
    "Trebich": 0,
    "Triygylnika": 0,
    # Ф
    "Fakulteta": 0,
    "Filipovci": 0,
    "Fondovi jilishta": 0,
    # Х
    "Hadji Dimityr": 0,
    "Hipodruma": 1,
    "Hladilnika": 0,
    "Hristo Botev": 0,
    # Ц
    "Centyr": 6,
    # Ч
    "Chelopechene": 0,
    # Я
    "Yavorov": 0,
}


# PARKS: 'Vyrtopo', 'Park-muzei  Vrana', 'Drujba', 'Studentski', 'Vitosha', 'Borisova gradina', 'Iujen park',
#        'Voenna akademia', 'Zaimov', 'Ovcha kupel', 'Zapaden park', 'Bratska mogila', 'Severen park', 'Loven park',
# 	     'Park Kambanite','Park Vuzrajdane','Park Slavia' N.B. No small areas marked as parks 
SOFIA_NEIGHBOURHOOD_PARK_TRUE_FALSE_MAPPING = {
    "7th 11th kilometer": False,
    # А
    "Abdovica": False,
    # Б
    "Banishora": False,
    "Belite brezi": True,
    "Benkovski": False,
    "Borovo": True,
    "Botunets": False,
    "Botunets 2": False,
    "Boyana": True,
    "Bukston": True,
    # В
    "Vitosha": True,
    "Voenna rampa": False,
    "Vrajdebna": False,
    "Vrybnitsa 1": False,
    "Vrybnitsa 2": False,
    # Г
    "Gevgeliski": False,
    "Geo Milev": True,
    "Gorna Banya": False,
    "Gorublyane": True,
    "Gotse Delchev": True,
    "Gradina": False,
    # Д
    "Dianabad": True,
    "Dimityr Milenkov": False,
    "Doktorski pametnik": True,
    "Dragalevtsi": True,
    "Drujba 1": True,
    "Drujba 2": True,
    "Durvenitsa": True,
    # Е
    "Eksperimentalen": False,
    # З
    "Zapaden park": True,
    "Zaharna fabrika": True,
    "Zona B-18": True,
    "Zona B-19": True,
    "Zona B-5": True,
    "Zona B-5-3": True,
    # И
    "Ivan Vazov": True,
    "Izgrev": True,
    "Iztok": True,
    "Ilinden": True,
    "Iliantsi": True,
    # К
    "Karpuzitsa": True,
    "Knyajevo": True,
    "Krasna polyana 1": True,
    "Krasna polyana 2": True,
    "Krasna polyana 3": True,
    "Krasno selo": True,
    "Kremikovtsi": False,
    "Krystova vada": True,
    # Л
    "Lagera": True,
    "Levski": False,
    "Levski V": False,
    "Levski G": False,
    "Letishte Sofia": False,
    "Lozenets": True,
    "Lulin - centyr": False,
    "Lulin 1": False,
    "Lulin 2": False,
    "Lulin 3": False,
    "Lulin 4": False,
    "Lulin 5": False,
    "Lulin 6": True,
    "Lulin 7": True,
    "Lulin 8": False,
    "Lulin 9": False,
    "Lulin 10": True,
    # М
    "Malashevtsi": False,
    "Malinova dolina": False,
    "Manastirski livadi": True,
    "Medicinska akademia": True,
    "Mladost 1": False,
    "Mladost 1A": False,
    "Mladost 2": True,
    "Mladost 3": False,
    "Mladost 4": True,
    "Moderno predgradie": False,
    "Musagenitsa": False,
    # Н
    "Nadejda 1": False,
    "Nadejda 2": False,
    "Nadejda 3": False,
    "Nadejda 4": True,
    "NPZ Iztok": False,
    "NPZ Iskyr": False,
    "NPZ Sredets": False,
    "NPZ Hadji Dimityr": False,
    # О
    "Obelya": False,
    "Obelya 1": False,
    "Obelya 2": False,
    "Oborishte": True,
    "Ovcha kupel": False,
    "Ovcha kupel 1": False,
    "Ovcha kupel 2": False,
    "Orlandovci": False,
    # П
    "Pavlovo": False,
    "PZ Iliyanci": False,
    "PZ Hladilnika": False,
    "Poduyane": False,
    "Poligona": False,
    # Р
    "Razsadnika": False,
    "Reduta": True,
    "Republika": False,
    "Republika 2": False,
    # C
    "Sveta Troica": True,
    "Svoboda": True,
    "Serdika": True,
    "Seslavci": False,
    "Simeonovo": True,
    "Slavia": True,
    "Slatina": True,
    "SPZ Moderno predgradie": False,
    "SPZ Slatina": False,
    "Strelbishte": True,
    "Studentski grad": True,
    "Suhata reka": False,
    "Suhodol": False,
    # Т
    "Tolstoy": False,
    "Trebich": False,
    "Triygylnika": False,
    # Ф
    "Fakulteta": False,
    "Filipovci": False,
    "Fondovi jilishta": False,
    # Х
    "Hadji Dimityr": False,
    "Hipodruma": False,
    "Hladilnika": True,
    "Hristo Botev": False,
    # Ц
    "Centyr": True,
    # Ч
    "Chelopechene": False,
    # Я
    "Yavorov": True,
}


# Data from: https://www.sofia.bg/web/guest/landscaped-areas-in-the-district-of-sofia
# TODO: Compare old and updated green areas by model tests with benchmark
SOFIA_REGIONS_GREEN_MAPPING = {
    "Sredets_Oborishte": 903.23,  # Centyr is the sum of Sredets and Oborishte
    "Sredets": 722.27,
    "Krasno selo": 150.21,
    "Vazrazhdane": 33.51,
    "Oborishte": 180.96,
    "Serdika": 66.13,
    "Poduyane": 147.09,
    "Slatina": 201.0,
    "Izgrev": 50.56,
    "Lozenets": 149.75,
    "Triadica": 217.86,
    "Krasna polyana": 95.70,
    "Ilinden": 607.50,
    "Nadezhda": 17.45,
    "Iskar": 357.89,  # Without park Vrana
    "Mladost": 411.40,
    "Studentski": 227.94,
    "Vitosha": 73.43,
    "Ovcha kupel": 115.33,
    "Lyulin": 53.30,
    "Vrabnitsa": 43.98,
    "Novi iskar": 143.70,
    "Kremikovtsi": 323.72,
    "Pancharevo": 302.08,
    "Bankya": 41.16,
}

SOFIA_REGIONS_GREEN_MAPPING_UPDATED = {
    "Sredets_Oborishte": 903.23,  # Centyr is the sum of Sredets and Oborishte
    "Sredets": 670.75,
    "Krasno selo": 97.95,
    "Vazrazhdane": 33.51,
    "Oborishte": 147.63,
    "Serdika": 66.0,
    "Poduyane": 100.13,
    "Slatina": 200.0,
    "Izgrev": 41.75,
    "Lozenets": 144.65,
    "Triadica": 213.22,
    "Krasna polyana": 95.70,
    "Ilinden": 599.33,
    "Nadezhda": 21.8,
    "Iskar": 81.4,  # Without park Vrana
    "Mladost": 53.7,
    "Studentski": 227.4,
    "Vitosha": 47.2,
    "Ovcha kupel": 113.4,
    "Lyulin": 10.3,
    "Vrabnitsa": 43.98,
    "Novi iskar": 115.87,
    "Kremikovtsi": 251.44,
    "Pancharevo": 265.81,
    "Bankya": 37.8,
}

# Data from official statistics 2011
SOFIA_REGIONS_POPULATION_MAPPING = {
    "Sredets_Oborishte": 63483,
    "Sredets": 32423,
    "Krasno selo": 83552,
    "Vazrazhdane": 37303,
    "Oborishte": 31060,
    "Serdika": 46949,
    "Poduyane": 76672,
    "Slatina": 66702,
    "Izgrev": 30896,
    "Lozenets": 53080,
    "Triadica": 63451,
    "Krasna polyana": 58234,
    "Ilinden": 33236,
    "Nadezhda": 67905,
    "Iskar": 63248,
    "Mladost": 102899,
    "Studentski": 71961,
    "Vitosha": 61467,
    "Ovcha kupel": 54320,
    "Lyulin": 114910,
    "Vrabnitsa": 47969,
    "Novi iskar": 28991,
    "Kremikovtsi": 23641,
    "Pancharevo": 28586,
    "Bankya": 12136,
}

# For scraper
SOFIA_APARTMENT_TYPES_MAPPING = {
    "1-STAEN": 1,
    "2-STAEN": 2,
    "3-STAEN": 3,
    "4-STEAEN": 4,
    "MNOGOSTAEN": 5,
    "MEZONET": 6,
    "ATELIE, TAVAN": 8,  # Not a typo
}

SOFIA_BG_EN_NEIGHBOURHOOD_MAPPING = {
    "7-ми 11-ти километър": "7th 11th kilometer",
    # А
    "Абдовица": "Abdovica",
    # Б
    "Банишора": "Banishora",
    "Белите брези": "Belite brezi",
    "Бенковски": "Benkovski",
    "Борово": "Borovo",
    "Ботунец": "Botunets",
    "Ботунец 2": "Botunets 2",
    "Бояна": "Boyana",
    "Бъкстон": "Bukston",
    # В
    "Витоша": "Vitosha",
    "Военна рампа": "Voenna rampa",
    "Враждебна": "Vrajdebna",
    "Връбница 1": "Vrybnitsa 1",
    "Връбница 2": "Vrybnitsa 2",
    # Г
    "Гевгелийски": "Gevgeliski",
    "Гео Милев": "Geo Milev",
    "Горна баня": "Gorna Banya",
    "Горубляне": "Gorublyane",
    "Гоце Делчев": "Gotse Delchev",
    "Градина": "Gradina",
    # Д
    "Дианабад": "Dianabad",
    "Димитър Миленков": "Dimityr Milenkov",
    "Докторски паметник": "Doktorski pametnik",
    "Драгалевци": "Dragalevtsi",
    "Дружба 1": "Drujba 1",
    "Дружба 2": "Drujba 2",
    "Дървеница": "Durvenitsa",
    # Е
    "Експериментален": "Eksperimentalen",
    # З
    "Западен парк": "Zapaden park",
    "Захарна фабрика": "Zaharna fabrika",
    "Зона Б-18": "Zona B-18",
    "Зона Б-19": "Zona B-19",
    "Зона Б-5": "Zona B-5",
    "Зона Б-5-3": "Zona B-5-3",
    # И
    "Иван Вазов": "Ivan Vazov",
    "Изгрев": "Izgrev",
    "Изток": "Iztok",
    "Илинден": "Ilinden",
    "Илиянци": "Iliantsi",
    # К
    "Карпузица": "Karpuzitsa",
    "Княжево": "Knyajevo",
    "Красна поляна 1": "Krasna polyana 1",
    "Красна поляна 2": "Krasna polyana 2",
    "Красна поляна 3": "Krasna polyana 3",
    "Красно село": "Krasno selo",
    "Кремиковци": "Kremikovtsi",
    "Кръстова вада": "Krystova vada",
    # Л
    "Лагера": "Lagera",
    "Левски": "Levski",
    "Левски В": "Levski V",
    "Левски Г": "Levski G",
    "Летище София": "Letishte Sofia",
    "Лозенец": "Lozenets",
    "Люлин - център": "Lulin - centyr",
    "Люлин 1": "Lulin 1",
    "Люлин 2": "Lulin 2",
    "Люлин 3": "Lulin 3",
    "Люлин 4": "Lulin 4",
    "Люлин 5": "Lulin 5",
    "Люлин 6": "Lulin 6",
    "Люлин 7": "Lulin 7",
    "Люлин 8": "Lulin 8",
    "Люлин 9": "Lulin 9",
    "Люлин 10": "Lulin 10",
    # М
    "Малашевци": "Malashevtsi",
    "Малинова долина": "Malinova dolina",
    "Манастирски ливади": "Manastirski livadi",
    "Медицинска академия": "Medicinska akademia",
    "Младост 1": "Mladost 1",
    "Младост 1А": "Mladost 1A",
    "Младост 2": "Mladost 2",
    "Младост 3": "Mladost 3",
    "Младост 4": "Mladost 4",
    "Модерно предградие": "Moderno predgradie",
    "Мусагеница": "Musagenitsa",
    # Н
    "Надежда 1": "Nadejda 1",
    "Надежда 2": "Nadejda 2",
    "Надежда 3": "Nadejda 3",
    "Надежда 4": "Nadejda 4",
    "НПЗ Изток": "NPZ Iztok",
    "НПЗ Искър": "NPZ Iskyr",
    "НПЗ Средец": "NPZ Sredets",
    "НПЗ Хаджи Димитър": "NPZ Hadji Dimityr",
    # О
    "Обеля": "Obelya",
    "Обеля 1": "Obelya 1",
    "Обеля 2": "Obelya 2",
    "Оборище": "Oborishte",
    "Овча купел": "Ovcha kupel",
    "Овча купел 1": "Ovcha kupel 1",
    "Овча купел 2": "Ovcha kupel 2",
    "Орландовци": "Orlandovci",
    # П
    "Павлово": "Pavlovo",
    "ПЗ Илиянци": "PZ Iliyanci",
    "ПЗ Хладилника": "PZ Hladilnika",
    "Подуяне": "Poduyane",
    "Полигона": "Poligona",
    # Р
    "Разсадника": "Razsadnika",
    "Редута": "Reduta",
    "Република": "Republika",
    "Република 2": "Republika 2",
    # C
    "Света Троица": "Sveta Troica",
    "Свобода": "Svoboda",
    "Сердика": "Serdika",
    "Сеславци": "Seslavci",
    "Симеоново": "Simeonovo",
    "Славия": "Slavia",
    "Слатина": "Slatina",
    "СПЗ Модерно предградие": "SPZ Moderno predgradie",
    "СПЗ Слатина": "SPZ Slatina",
    "Стрелбище": "Strelbishte",
    "Студентски град": "Studentski grad",
    "Сухата река": "Suhata reka",
    "Суходол": "Suhodol",
    # Т
    "Толстой": "Tolstoy",
    "Требич": "Trebich",
    "Триъгълника": "Triygylnika",
    # Ф
    "Факултета": "Fakulteta",
    "Филиповци": "Filipovci",
    "Фондови жилища": "Fondovi jilishta",
    # Х
    "Хаджи Димитър": "Hadji Dimityr",
    "Хиподрума": "Hipodruma",
    "Хладилника": "Hladilnika",
    "Христо Ботев": "Hristo Botev",
    # Ц
    "Център": "Centyr",
    # Ч
    "Челопечене": "Chelopechene",
    # Я
    "Яворов": "Yavorov",
}

# All values are manually checked and confirmed
SOFIA_NEIGHBOURHOOD_TO_REGION_MAPPING = {
    "7th 11th kilometer": "Mladost",
    # А
    "Abdovica": "Iskar",
    # Б
    "Banishora": "Serdika",
    "Belite brezi": "Krasno selo",
    "Benkovski": "Serdika",
    "Borovo": "Krasno selo",
    "Botunets": "Kremikovtsi",
    "Botunets 2": "Kremikovtsi",
    "Boyana": "Vitosha",
    "Bukston": "Vitosha",
    # В
    "Vitosha": "Lozenets",
    "Voenna rampa": "Serdika",
    "Vrajdebna": "Kremikovtsi",
    "Vrybnitsa 1": "Vrabnitsa",
    "Vrybnitsa 2": "Vrabnitsa",
    # Г
    "Gevgeliski": "Ilinden",
    "Geo Milev": "Slatina",
    "Gorna Banya": "Ovcha kupel",
    "Gorublyane": "Mladost",
    "Gotse Delchev": "Triadica",
    "Gradina": "Vitosha",
    # Д
    "Dianabad": "Izgrev",
    "Dimityr Milenkov": "Iskar",
    "Doktorski pametnik": "Sredets_Oborishte",
    "Dragalevtsi": "Vitosha",
    "Drujba 1": "Iskar",
    "Drujba 2": "Iskar",
    "Durvenitsa": "Studentski",
    # Е
    "Eksperimentalen": "Mladost",
    # З
    "Zapaden park": "Krasna polyana",
    "Zaharna fabrika": "Ilinden",
    "Zona B-18": "Vazrazhdane",
    "Zona B-19": "Vazrazhdane",
    "Zona B-5": "Vazrazhdane",
    "Zona B-5-3": "Vazrazhdane",
    # И
    "Ivan Vazov": "Triadica",
    "Izgrev": "Izgrev",
    "Iztok": "Izgrev",
    "Ilinden": "Ilinden",
    "Iliantsi": "Nadezhda",
    # К
    "Karpuzitsa": "Vitosha",
    "Knyajevo": "Vitosha",
    "Krasna polyana 1": "Krasna polyana",
    "Krasna polyana 2": "Krasna polyana",
    "Krasna polyana 3": "Krasna polyana",
    "Krasno selo": "Krasno selo",
    "Kremikovtsi": "Kremikovtsi",
    "Krystova vada": "Triadica",
    # Л
    "Lagera": "Krasno selo",
    "Levski": "Poduyane",
    "Levski V": "Poduyane",
    "Levski G": "Poduyane",
    "Letishte Sofia": "Poduyane",
    "Lozenets": "Lozenets",
    "Lulin - centyr": "Lyulin",
    "Lulin 1": "Lyulin",
    "Lulin 2": "Lyulin",
    "Lulin 3": "Lyulin",
    "Lulin 4": "Lyulin",
    "Lulin 5": "Lyulin",
    "Lulin 6": "Lyulin",
    "Lulin 7": "Lyulin",
    "Lulin 8": "Lyulin",
    "Lulin 9": "Lyulin",
    "Lulin 10": "Lyulin",
    # М
    "Malashevtsi": "Serdika",
    "Malinova dolina": "Mladost",
    "Manastirski livadi": "Vitosha",
    "Medicinska akademia": "Krasno selo",
    "Mladost 1": "Mladost",
    "Mladost 1A": "Mladost",
    "Mladost 2": "Mladost",
    "Mladost 3": "Mladost",
    "Mladost 4": "Mladost",
    "Moderno predgradie": "Vrabnitsa",
    "Musagenitsa": "Studentski",
    # Н
    "Nadejda 1": "Nadezhda",
    "Nadejda 2": "Nadezhda",
    "Nadejda 3": "Nadezhda",
    "Nadejda 4": "Nadezhda",
    "NPZ Iztok": "Mladost",
    "NPZ Iskyr": "Iskar",
    "NPZ Sredets": "Krasna polyana",
    "NPZ Hadji Dimityr": "Poduyane",
    # О
    "Obelya": "Vrabnitsa",
    "Obelya 1": "Vrabnitsa",
    "Obelya 2": "Vrabnitsa",
    "Oborishte": "Oborishte",
    "Ovcha kupel": "Ovcha kupel",
    "Ovcha kupel 1": "Ovcha kupel",
    "Ovcha kupel 2": "Ovcha kupel",
    "Orlandovci": "Serdika",
    # П
    "Pavlovo": "Vitosha",
    "PZ Iliyanci": "Nadezhda",
    "PZ Hladilnika": "Lozenets",
    "Poduyane": "Poduyane",
    "Poligona": "Mladost",
    # Р
    "Razsadnika": "Krasna polyana",
    "Reduta": "Slatina",
    "Republika": "Lyulin",
    "Republika 2": "Lyulin",
    # C
    "Sveta Troica": "Ilinden",
    "Svoboda": "Nadezhda",
    "Serdika": "Serdika",
    "Seslavci": "Kremikovtsi",
    "Simeonovo": "Vitosha",
    "Slavia": "Krasno selo",
    "Slatina": "Slatina",
    "SPZ Moderno predgradie": "Vrabnitsa",
    "SPZ Slatina": "Slatina",
    "Strelbishte": "Triadica",
    "Studentski grad": "Studentski",
    "Suhata reka": "Poduyane",
    "Suhodol": "Ovcha kupel",
    # Т
    "Tolstoy": "Ovcha kupel",
    "Trebich": "Nadezhda",
    "Triygylnika": "Nadezhda",
    # Ф
    "Fakulteta": "Krasna polyana",
    "Filipovci": "Lyulin",
    "Fondovi jilishta": "Serdika",
    # Х
    "Hadji Dimityr": "Poduyane",
    "Hipodruma": "Krasno selo",
    "Hladilnika": "Lozenets",
    "Hristo Botev": "Slatina",
    # Ц
    "Centyr": "Sredets_Oborishte",
    # Ч
    "Chelopechene": "Kremikovtsi",
    # Я
    "Yavorov": "Sredets"
}
