# Generated by Django 3.1.2 on 2020-10-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartmentType', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constructionType', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='durationMonths',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='history',
            name='apartmentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web_app.apartmenttype'),
        ),
        migrations.AlterField(
            model_name='history',
            name='constructionType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='web_app.constructiontype'),
        ),
    ]
