# Generated by Django 3.1.2 on 2020-11-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web_app', '0003_auto_20201103_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='subscriptionDate',
            new_name='subscriptionStartDate',
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscriptionEndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
