# Generated by Django 3.1.2 on 2020-11-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web_app', '0004_auto_20201107_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscriptionEndDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscriptionStartDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
