# Generated by Django 3.1.2 on 2020-11-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0005_auto_20201107_2350'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60, verbose_name='email')),
                ('title', models.CharField(max_length=30)),
                ('message', models.TextField()),
            ],
        ),
    ]
