# Generated by Django 3.1.2 on 2020-11-11 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_auto_20201111_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='floor',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='history',
            name='pricePrediction',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5000)]),
        ),
        migrations.AlterField(
            model_name='history',
            name='priceSQM',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='history',
            name='squareMeters',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='history',
            name='year',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1880), django.core.validators.MaxValueValidator(2030)]),
        ),
    ]
