# Generated by Django 3.1.2 on 2020-11-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('web_app', '0007_auto_20201111_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='predictionsLeft',
            field=models.IntegerField(default=0),
        ),
    ]
