# Generated by Django 3.1.2 on 2020-12-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_contactmessage'),
        ('web_app', '0008_customuser_predictionsleft'),
    ]

    operations = [
    ]
